"""Table of Contents entries — (title, page, indent_level)."""

TOC_ENTRIES = [
    # Preliminary (roman numerals)
    ("BONAFIDE CERTIFICATE", "i", 0),
    ("PROJECT APPROVAL SHEET", "ii", 0),
    ("DECLARATION", "iii", 0),
    ("CERTIFICATE FROM SUPERVISOR", "iv", 0),
    ("ACKNOWLEDGEMENT", "v", 0),
    ("ABSTRACT", "vi", 0),
    ("TABLE OF CONTENTS", "vii", 0),
    ("LIST OF FIGURES", "ix", 0),
    ("LIST OF TABLES", "x", 0),
    ("LIST OF ABBREVIATIONS AND ACRONYMS", "xi", 0),
    ("", "", 0),
    # Chapter 1
    ("CHAPTER 1 – INTRODUCTION", "1", 0),
    ("1.1 Introduction to Artificial Intelligence", "1", 1),
    ("1.2 Voice-Controlled Systems Overview", "2", 1),
    ("1.3 Need for AI-Based Study Assistants", "2", 1),
    ("1.4 Problem Statement", "3", 1),
    ("1.5 Motivation of the Project", "3", 1),
    ("1.6 Objectives of the Project", "4", 1),
    ("1.7 Scope of the Project", "5", 1),
    ("1.8 Proposed Solution", "5", 1),
    ("1.9 Applications of the System", "6", 1),
    ("1.10 Advantages of the Proposed System", "6", 1),
    ("1.11 Organization of the Report", "7", 1),
    ("", "", 0),
    # Chapter 2
    ("CHAPTER 2 – LITERATURE SURVEY", "8", 0),
    ("2.1 Introduction", "8", 1),
    ("2.2 Existing Voice Assistant Technologies", "8", 1),
    ("2.3 AI in Smart Education Systems", "9", 1),
    ("2.4 Speech Recognition Techniques", "9", 1),
    ("2.5 Natural Language Processing Approaches", "10", 1),
    ("2.6 Machine Learning Models Used in Assistants", "10", 1),
    ("2.7 Comparative Analysis of Existing Systems", "11", 1),
    ("2.8 Research Gaps Identified", "11", 1),
    ("2.9 Summary", "12", 1),
    ("", "", 0),
    # Chapter 3
    ("CHAPTER 3 – SYSTEM ANALYSIS", "13", 0),
    ("3.1 Existing System", "13", 1),
    ("3.2 Drawbacks of Existing System", "13", 1),
    ("3.3 Proposed System", "14", 1),
    ("3.4 Feasibility Study", "14", 1),
    ("3.4.1 Technical Feasibility", "14", 2),
    ("3.4.2 Economic Feasibility", "15", 2),
    ("3.4.3 Operational Feasibility", "15", 2),
    ("3.5 System Requirements", "15", 1),
    ("3.5.1 Hardware Requirements", "16", 1),
    ("3.5.2 Software Requirements", "16", 1),
    ("3.6 Functional Requirements", "17", 1),
    ("3.7 Non-Functional Requirements", "17", 1),
    ("3.8 System Architecture Overview", "18", 1),
    ("", "", 0),
    # Chapter 4 (expanded)
    ("CHAPTER 4 – DESIGN METHODOLOGY", "19", 0),
    ("4.1 Introduction", "19", 1),
    ("4.2 Architecture of the Proposed System", "20", 1),
    ("4.2.1 End-to-End Development Phases", "21", 2),
    ("4.2.2 REST API and Endpoint Design", "22", 2),
    ("4.2.3 Prompt Engineering and Source Grounding Strategy", "22", 2),
    ("4.3 Module Description", "23", 1),
    ("4.3.1 Voice Input Module", "23", 2),
    ("4.3.2 Speech-to-Text Module", "24", 2),
    ("4.3.3 NLP Processing Module", "24", 2),
    ("4.3.4 AI Response Generation Module", "25", 2),
    ("4.3.5 Database Module", "26", 2),
    ("4.3.6 User Interface Module", "26", 2),
    ("4.3.7 Error Handling and Resilience", "27", 2),
    ("4.4 Data Flow Diagram (DFD)", "26", 1),
    ("4.5 Use Case Diagram", "28", 1),
    ("4.6 Sequence Diagram", "29", 1),
    ("4.7 Activity Diagram", "30", 1),
    ("4.8 ER Diagram / Database Design", "31", 1),
    ("4.9 Algorithm Design", "32", 1),
    ("4.10 Flowchart of System Operation", "33", 1),
    ("4.11 Security and Privacy Considerations", "34", 1),
    ("", "", 0),
    # Chapter 5
    ("CHAPTER 5 – IMPLEMENTATION", "35", 0),
    ("5.1 Introduction", "35", 1),
    ("5.2 Development Environment", "36", 1),
    ("5.3 Tools and Technologies Used", "36", 1),
    ("5.4 Coding Methodology", "37", 1),
    ("5.5 Implementation of Modules", "38", 1),
    ("5.6 Integration of Voice Commands", "38", 1),
    ("5.7 AI Model Training and Testing", "39", 1),
    ("5.8 User Authentication Process", "39", 1),
    ("5.9 API Integration", "40", 1),
    ("5.10 Screenshots of Implementation", "40", 1),
    ("", "", 0),
    # Chapter 6
    ("CHAPTER 6 – RESULTS AND DISCUSSION", "41", 0),
    ("6.1 Experimental Setup", "41", 1),
    ("6.2 Test Cases", "42", 1),
    ("6.3 Performance Evaluation", "43", 1),
    ("6.4 Accuracy of Speech Recognition", "43", 1),
    ("6.5 Response Time Analysis", "44", 1),
    ("6.6 Comparative Performance Analysis", "44", 1),
    ("6.7 Output Screenshots", "45", 1),
    ("6.8 Discussion of Results", "45", 1),
    ("6.9 Limitations of the System", "46", 1),
    ("", "", 0),
    # Chapter 7
    ("CHAPTER 7 – CONCLUSION AND FUTURE SCOPE", "47", 0),
    ("7.1 Conclusion", "47", 1),
    ("7.2 Achievements of the Project", "47", 1),
    ("7.3 Future Enhancements", "48", 1),
    ("7.4 Real-Time Industrial Applications", "48", 1),
    ("7.5 Final Remarks", "49", 1),
    ("", "", 0),
    ("REFERENCES", "50", 0),
    ("APPENDICES", "51", 0),
]
